### ISSUE TITLE
Cannot find symbol MainActivity

### ISSUE THREAD

**Issue by iegik** [cstew/Splash#4]
https://github.com/cstew/Splash/blob/master/app/src/main/java/com/bignerdranch/android/splash/SplashActivity.java#L13: error: cannot find symbol
```
        Intent intent = new Intent(this, MainActivity.class);
                                         ^
  symbol:   class MainActivity
  location: class SplashActivity
```

**Comment by cstew** [comment]
It looks like the project import/open wasn't done correctly. Two questions:

1. Did the project ever compile/run successfully for you? 
2. How did you open/import the project?

**Comment by cheddarwhizzy** [comment]
PS, this is due to the fact that the package name at the top of `SplashActivity.java` should be the same as the one at the top of your app's `MainActivity.java`. If you copy and pasted the code from this repo into your react native app like I did, you'll get this error. Make sure to change `package com.bignerdranch.android.splash;` to `package com.YOUR_APP_NAME_HERE`. Hope this helps someone else out there.
