### ISSUE TITLE
Can we set a time limit

### ISSUE THREAD

**Issue by ballySingh** [cstew/Splash#8]
Is it possible to add a time limit on how long the splash screen appears? 

I only see it half a second.

**Comment by cstew** [comment]
You can add a `SystemClock.sleep(2000)` in there if you want but I wouldn't recommend it. The point of this technique is to only show the screen while you are actually loading. Otherwise, you're just wasting the user's time. 

You can read more about it in my article if you haven't already: https://www.bignerdranch.com/blog/splash-screens-the-right-way/
